#! /bin/bash

actual_brightness=$( cat /sys/class/backlight/acpi_video0/actual_brightness )
if [ ${actual_brightness} -lt 10 ]; then
	echo $(( actual_brightness + 1 )) >"/sys/class/backlight/acpi_video0/brightness"
fi

