#!/bin/bash 

#DEVICE_ID_FILE_NAME_PATTERN="^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]$"


ALL_EHCI_HCD_DEVICE_ID=("0000:00:1d.0" "0000:00:1a.0")
EHCI_HCD_FOLDER_PATH="/sys/bus/pci/drivers/ehci_hcd"

ALL_XHCI_HCD_DEVICE_ID=("0000:07:00.0")
XHCI_HCD_FOLDER_PATH="/sys/bus/pci/drivers/xhci_hcd"

unbind_all_ehci_hcd()
{
	echo "Unbinding USB2.0 devices: "
	for device_id in "${ALL_EHCI_HCD_DEVICE_ID[@]}"; do
		echo " --> ${device_id#@}"
		echo -n "${device_id#@}" >"${EHCI_HCD_FOLDER_PATH}/unbind"
	done
	return 0
}

unbind_all_xhci_hcd()
{
	echo "Unbinding USB3.0 devices: "
	for device_id in "${ALL_XHCI_HCD_DEVICE_ID[@]}"; do
		echo " --> ${device_id#@}"
		echo -n "${device_id#@}" >"${XHCI_HCD_FOLDER_PATH}/unbind"
	done
	return 0
}


unbind_all_ehci_hcd
unbind_all_xhci_hcd

exit 0
